github:
  description: Easy and Repeatable Kubernetes Development
  license: Apache-2.0
  homepage: https://skaffold.dev/
  created: 2018-01-23
  archived: false
  star: 15888
  watcher: 181
  fork: 1705
  release: 200
  contributor: 454
  pullRequest: 994
  issue: 4277
  lastCommit: 2026-08-20
  lastRelease: 2026-07-23
language:
  Go: 9607380
  JavaScript: 143625
  Shell: 68385
  HTML: 49497
  Dockerfile: 33931
  Makefile: 18210
  CSS: 15208
  Go Template: 7506
  Python: 6040
  NSIS: 4392
  Java: 3625
  Batchfile: 2165
  Starlark: 1925
  PHP: 1864
  Mustache: 1078
  Ruby: 897
  Groovy: 615
  TypeScript: 326
  Procfile: 71
totalLine: 9966740
detail:
  head: 359a940
recent:
  last30d:
    since: 2026-07-25
    release: 0
    mergedPR: 2
    openPR: 4
    closedIssue: 0
    openIssue: 2
    commit: 2
  last90d:
    since: 2026-05-26
    release: 3
    mergedPR: 25
    openPR: 16
    closedIssue: 1
    openIssue: 12
    commit: 24
  last180d:
    since: 2026-02-25
    release: 11
    mergedPR: 74
    openPR: 34
    closedIssue: 7
    openIssue: 17
    commit: 70
  last360d:
    since: 2025-08-29
    release: 14
    mergedPR: 123
    openPR: 52
    closedIssue: 13
    openIssue: 36
    commit: 118
collectedAt: 2026-08-24T12:55:10Z
